# Generated by Django 3.2.19 on 2024-03-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20240305_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ImageField(default='', upload_to='CategoryImages'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='images',
            field=models.ImageField(default='', upload_to='CategoryImages'),
        ),
    ]
